'use strict';
const http=require('http'); const fs=require('fs'); const path=require('path'); const {z}=require('zod');
const {db,getConfig}=require('./server/db'); const auth=require('./server/auth'); const wallet=require('./server/wallet'); const pvp=require('./server/pvp'); const payments=require('./server/payments'); const aml=require('./server/aml'); const telegram=require('./server/telegram'); const admin=require('./server/admin'); const websocket=require('./server/websocket'); const {audit}=require('./server/audit');
const {readJson,json,clientIp,cookie,randomToken,safeFile}=require('./server/utils');
const PORT=Number(process.env.PORT||8080), PUBLIC=path.join(__dirname,'public'), PROD=process.env.NODE_ENV==='production';
const depositSchema=z.object({method:z.enum(['bkash','nagad']),amount:z.coerce.number().positive().max(100000000),transactionId:z.string().trim().min(3).max(120)});
const withdrawalSchema=z.object({method:z.enum(['bkash','nagad']),accountNumber:z.string().trim().regex(/^\+?[0-9]{8,15}$/),amount:z.coerce.number().positive().max(100000000),sourceBucket:z.enum(['winnings','cash','bonus']).default('winnings')});
const matchSchema=z.object({entryFee:z.coerce.number().nonnegative().max(1000000),betAmount:z.coerce.number().positive().max(100000000)});
const configPatchSchema=z.object({welcomeBonus:z.number().min(0).max(1000000).optional(),bonusWithdrawable:z.boolean().optional(),pvpEnabled:z.boolean().optional(),entryFee:z.number().min(0).max(1000000).optional(),minBet:z.number().min(0).max(100000000).optional(),maxBet:z.number().min(0).max(100000000).optional(),turnSeconds:z.number().int().min(3).max(120).optional(),timeoutStrikes:z.number().int().min(1).max(10).optional(),extraTurnOnSix:z.boolean().optional(),extraTurnOnCapture:z.boolean().optional(),minDeposit:z.number().min(0).max(100000000).optional(),maxDeposit:z.number().min(0).max(100000000).optional(),minWithdraw:z.number().min(0).max(100000000).optional(),maxWithdraw:z.number().min(0).max(100000000).optional(),withdrawalFeePercent:z.number().min(0).max(25).optional(),dailyWithdrawLimit:z.number().min(0).max(100000000).optional(),amlThreshold:z.number().min(0).max(100000000).optional(),appNotice:z.string().max(1000).optional(),supportText:z.string().max(2000).optional(),withdrawFromCash:z.boolean().optional(),dailyDepositLimit:z.number().min(0).max(100000000).optional(),disconnectLoss:z.boolean().optional()}).strict();

const rate=new Map();
function limited(key,max,windowMs=60000){const t=Date.now(); let r=rate.get(key); if(!r||r.reset<=t)r={n:0,reset:t+windowMs}; r.n++; rate.set(key,r); return r.n>max;}
setInterval(()=>{const t=Date.now();for(const[k,v]of rate)if(v.reset<t)rate.delete(k);},300000).unref();
function needUser(req){const a=auth.fromRequest(req); if(!a)throw status('AUTH_REQUIRED',401); if(limited(`u:${a.user.id}`,90))throw status('RATE_LIMIT',429); return a;}
function needAdmin(req,mutating=false){const s=admin.verify(req); if(!s)throw status('ADMIN_AUTH_REQUIRED',401); if(mutating)admin.csrf(req,s); return s;}
function idemLookup(scope,actor,key){if(!key)throw status('IDEMPOTENCY_KEY_REQUIRED',400); const r=db.prepare('SELECT * FROM idempotency_keys WHERE scope=? AND actor_id=? AND key=?').get(scope,actor,key); if(r?.response_json)return {status:r.response_status,body:JSON.parse(r.response_json)}; if(r)throw status('IDEMPOTENCY_IN_PROGRESS',409); db.prepare('INSERT INTO idempotency_keys(scope,actor_id,key,created_at) VALUES(?,?,?,?)').run(scope,actor,key,Date.now()); return null;}
function idemSave(scope,actor,key,statusCode,body){db.prepare('UPDATE idempotency_keys SET response_status=?,response_json=? WHERE scope=? AND actor_id=? AND key=?').run(statusCode,JSON.stringify(body),scope,actor,key);}
async function moneyAction(req,res,scope,actor,fn){const key=String(req.headers['idempotency-key']||'').slice(0,120), old=idemLookup(scope,actor,key); if(old)return json(res,old.status,old.body); try{const body=await fn(); idemSave(scope,actor,key,200,body); return json(res,200,body);}catch(e){db.prepare('DELETE FROM idempotency_keys WHERE scope=? AND actor_id=? AND key=? AND response_json IS NULL').run(scope,actor,key); throw e;}}
function publicConfig(){const c=getConfig(); return {appNotice:c.appNotice,supportText:c.supportText,pvpEnabled:c.pvpEnabled,entryFee:c.entryFee,minBet:c.minBet,maxBet:c.maxBet,turnSeconds:c.turnSeconds,minDeposit:c.minDeposit,maxDeposit:c.maxDeposit,minWithdraw:c.minWithdraw,maxWithdraw:c.maxWithdraw};}
const server=http.createServer(async(req,res)=>{
  const ip=clientIp(req); if(limited(`ip:${ip}`,150))return json(res,429,{error:'RATE_LIMIT'});
  try{
    const url=new URL(req.url,`http://${req.headers.host||'localhost'}`), pathname=url.pathname;
    if(PROD){const proto=req.socket.encrypted?'https':(process.env.TRUST_PROXY==='1'?String(req.headers['x-forwarded-proto']||'').split(',')[0].trim():'http'); if(proto!=='https')return json(res,426,{error:'TLS_REQUIRED'});}
    if(pathname==='/api/health'&&req.method==='GET')return json(res,200,{ok:true,version:'12.0.0'});
    if(pathname==='/api/config'&&req.method==='GET')return json(res,200,publicConfig());
    if(pathname==='/api/payment-methods'&&req.method==='GET'){const kind=url.searchParams.get('kind')||'deposit'; return json(res,200,{items:db.prepare('SELECT id,kind,method,label,account_number FROM payment_methods WHERE enabled=1 AND kind=? ORDER BY created_at').all(kind)});}
    if(pathname==='/api/auth/signup'&&req.method==='POST'){if(limited(`auth:${ip}`,10))throw status('RATE_LIMIT',429); const u=await auth.signup(await readJson(req)); telegram.notify('account',u).catch(console.error); audit({actorType:'user',actorId:u.id,action:'signup',targetType:'user',targetId:u.id,ip}); return json(res,201,{user:u});}
    if(pathname==='/api/auth/login'&&req.method==='POST'){if(limited(`auth:${ip}`,10))throw status('RATE_LIMIT',429); const out=await auth.login(await readJson(req),{ip,userAgent:req.headers['user-agent']||''}); return json(res,200,{user:out.user},{'set-cookie':cookie('plh_session',out.token,{maxAge:auth.SESSION_MS,secure:PROD})});}
    if(pathname==='/api/auth/logout'&&req.method==='POST'){const a=needUser(req); auth.logout(a.token); return json(res,200,{ok:true},{'set-cookie':cookie('plh_session','',{maxAge:0,secure:PROD})});}
    if(pathname==='/api/me'&&req.method==='GET'){const a=needUser(req),w=db.prepare('SELECT * FROM wallets WHERE user_id=?').get(a.user.id); return json(res,200,{user:auth.publicUser(a.user),wallet:walletView(w)});}
    if(pathname==='/api/profile'&&req.method==='PATCH'){const a=needUser(req),x=z.object({displayName:z.string().trim().min(2).max(60).optional(),avatar:z.string().url().max(500).nullable().optional()}).parse(await readJson(req)); db.prepare('UPDATE users SET display_name=COALESCE(?,display_name),avatar=COALESCE(?,avatar),updated_at=? WHERE id=?').run(x.displayName??null,x.avatar??null,Date.now(),a.user.id); return json(res,200,{user:auth.publicUser(db.prepare('SELECT * FROM users WHERE id=?').get(a.user.id))});}
    if(pathname==='/api/responsible/self-exclude'&&req.method==='POST'){const a=needUser(req); db.prepare('UPDATE users SET self_excluded=1,updated_at=? WHERE id=?').run(Date.now(),a.user.id); audit({actorType:'user',actorId:a.user.id,action:'self_exclude',targetType:'user',targetId:a.user.id,ip}); return json(res,200,{ok:true});}
    if(pathname==='/api/responsible/cool-off'&&req.method==='POST'){const a=needUser(req),x=z.object({hours:z.number().int().min(24).max(24*365)}).parse(await readJson(req)),until=Date.now()+x.hours*3600000; db.prepare('UPDATE users SET cool_off_until=?,updated_at=? WHERE id=?').run(until,Date.now(),a.user.id); return json(res,200,{coolOffUntil:until});}
    if(pathname==='/api/responsible/deposit-limit'&&req.method==='POST'){const a=needUser(req),x=z.object({amount:z.number().positive().max(10000000)}).parse(await readJson(req)); db.prepare('UPDATE users SET daily_deposit_limit=?,updated_at=? WHERE id=?').run(Math.round(x.amount*100),Date.now(),a.user.id); return json(res,200,{ok:true});}
    if(pathname==='/api/deposits'&&req.method==='POST'){const a=needUser(req),input=depositSchema.parse(await readJson(req)); return await moneyAction(req,res,'create_deposit',a.user.id,async()=>{const d=payments.createDeposit(a.user.id,input); telegram.notify('deposit',{...d,username:a.user.username}).catch(console.error); return {deposit:depositView(d)};});}
    if(pathname==='/api/deposits'&&req.method==='GET'){const a=needUser(req); return json(res,200,{items:db.prepare('SELECT * FROM deposits WHERE user_id=? ORDER BY created_at DESC LIMIT 100').all(a.user.id).map(depositView)});}
    if(pathname==='/api/withdrawals'&&req.method==='POST'){const a=needUser(req),input=withdrawalSchema.parse(await readJson(req)); return await moneyAction(req,res,'create_withdrawal',a.user.id,async()=>{const w=payments.createWithdrawal(a.user.id,input); telegram.notify('withdrawal',{...w,username:a.user.username}).catch(console.error); return {withdrawal:withdrawView(w)};});}
    if(pathname==='/api/withdrawals'&&req.method==='GET'){const a=needUser(req); return json(res,200,{items:db.prepare('SELECT * FROM withdrawals WHERE user_id=? ORDER BY created_at DESC LIMIT 100').all(a.user.id).map(withdrawView)});}
    if(pathname==='/api/pvp/open'&&req.method==='GET'){needUser(req); return json(res,200,{items:pvp.listOpen()});}
    if(pathname==='/api/pvp/create'&&req.method==='POST'){const a=needUser(req),input=matchSchema.parse(await readJson(req)); return await moneyAction(req,res,'pvp_create',a.user.id,async()=>({match:pvp.createMatch(a.user.id,input)}));}
    let m=pathname.match(/^\/api\/pvp\/([^/]+)\/(join|cancel|dispute)$/); if(m&&req.method==='POST'){const a=needUser(req),matchId=m[1],act=m[2],input=await readJson(req); if(act==='join')return await moneyAction(req,res,'pvp_join',a.user.id,async()=>({match:pvp.joinMatch(a.user.id,matchId)})); if(act==='cancel'){const key=String(req.headers['idempotency-key']||''); return await moneyAction(req,res,'pvp_cancel',a.user.id,async()=>{pvp.cancelWaiting(a.user.id,matchId);return{ok:true};});} if(act==='dispute'){const reason=z.string().trim().min(3).max(500).parse(input.reason); const r=pvp.dispute(a.user.id,matchId,reason); telegram.notify('dispute',{id:r.id,matchId,reason}).catch(console.error); return json(res,201,r);}}

    if(pathname==='/api/admin/login'&&req.method==='POST'){if(limited(`adminlogin:${ip}`,8,10*60000))throw status('RATE_LIMIT',429); const body=await readJson(req), cookies=parseCookie(req), device=cookies.plh_admin_device||randomToken(24), out=admin.login(req,String(body.pin||''),device); const headers={'set-cookie':[cookie('plh_admin_device',device,{maxAge:365*24*3600000,secure:PROD}),cookie('plh_admin',out.token,{maxAge:Number(process.env.ADMIN_SESSION_TTL_MS||28800000),secure:PROD})]}; return json(res,200,{csrf:out.csrf,expiresAt:out.expiresAt},headers);}
    if(pathname==='/api/admin/dashboard'&&req.method==='GET'){needAdmin(req); return json(res,200,admin.dashboard());}
    if(pathname==='/api/admin/pending'&&req.method==='GET'){needAdmin(req); return json(res,200,admin.pending());}
    if(pathname==='/api/admin/users'&&req.method==='GET'){needAdmin(req); return json(res,200,{items:admin.users(url.searchParams.get('q')||'')});}
    if(pathname==='/api/admin/live-matches'&&req.method==='GET'){needAdmin(req); return json(res,200,{items:pvp.listLive()});}
    if(pathname==='/api/admin/ledger'&&req.method==='GET'){needAdmin(req); return json(res,200,{items:admin.ledgerRows(url.searchParams.get('limit'))});}
    if(pathname==='/api/admin/ledger.csv'&&req.method==='GET'){needAdmin(req); const data=Buffer.from(admin.ledgerCsv()); res.writeHead(200,{'content-type':'text/csv; charset=utf-8','content-disposition':'attachment; filename="ledger.csv"','content-length':data.length}); return res.end(data);}
    if(pathname==='/api/admin/audit'&&req.method==='GET'){needAdmin(req); return json(res,200,{items:admin.auditRows()});}
    if(pathname==='/api/admin/aml'&&req.method==='GET'){needAdmin(req); return json(res,200,{items:aml.report()});}
    if(pathname==='/api/admin/reconciliation'&&req.method==='GET'){needAdmin(req); return json(res,200,await admin.reconciliation(url.searchParams.get('date')||new Date().toISOString().slice(0,10)));}
    if(pathname==='/api/admin/config'&&req.method==='POST'){const s=needAdmin(req,true), next=configPatchSchema.parse(await readJson(req)), merged={...getConfig(),...next}; if(merged.minBet>merged.maxBet||merged.minDeposit>merged.maxDeposit||merged.minWithdraw>merged.maxWithdraw)throw status('INVALID_CONFIG_RANGE',400); const cfg=admin.setConfig(next); audit({actorType:'admin',actorId:s.id,action:'update_config',targetType:'config',details:next,ip}); return json(res,200,{config:cfg});}
    if(pathname==='/api/admin/payment-methods'&&req.method==='GET'){needAdmin(req);return json(res,200,{items:db.prepare('SELECT * FROM payment_methods ORDER BY created_at DESC').all()});}
    if(pathname==='/api/admin/payment-methods'&&req.method==='POST'){const s=needAdmin(req,true),r=admin.saveMethod(await readJson(req),s.id);return json(res,200,{item:r});}
    m=pathname.match(/^\/api\/admin\/(account|deposit|withdrawal)\/([^/]+)\/(approve|reject)$/); if(m&&req.method==='POST'){const s=needAdmin(req,true),kind=m[1],id=m[2],approve=m[3]==='approve'; return await moneyAction(req,res,`admin_${m[3]}_${kind}`,s.id,async()=>({ok:true,message:await admin.decide(kind,id,approve,s.id)}));}
    m=pathname.match(/^\/api\/admin\/users\/([^/]+)\/(status|adjust)$/); if(m&&req.method==='POST'){const s=needAdmin(req,true),id=m[1],act=m[2],body=await readJson(req); if(act==='status'){admin.setUserStatus(id,String(body.status),s.id);return json(res,200,{ok:true});} if(act==='adjust')return await moneyAction(req,res,'admin_adjust',s.id,async()=>({wallet:walletView(admin.adjustBalance(id,body,s.id))}));}
    m=pathname.match(/^\/api\/admin\/disputes\/([^/]+)\/(resolve|reject)$/); if(m&&req.method==='POST'){const s=needAdmin(req,true),body=await readJson(req); const statusName=m[2]==='resolve'?'resolved':'rejected'; const msg=admin.resolveDispute(m[1],statusName,String(body.resolution||statusName),s.id); return json(res,200,{ok:true,message:msg});}
    m=pathname.match(/^\/api\/admin\/matches\/([^/]+)\/force-end$/); if(m&&req.method==='POST'){const s=needAdmin(req,true),body=await readJson(req); return await moneyAction(req,res,'admin_force_end',s.id,async()=>{pvp.forceEnd(s.id,m[1],String(body.winnerId),String(body.reason||'admin_force_end'));return{ok:true};});}

    if(pathname.startsWith('/api/'))return json(res,404,{error:'NOT_FOUND'});
    return serveStatic(pathname,res);
  }catch(e){const code=e.issues?'VALIDATION_ERROR':(e.code||e.message||'SERVER_ERROR'); const st=e.status||({AUTH_REQUIRED:401,ADMIN_AUTH_REQUIRED:401,NOT_FOUND:404,INVALID_CREDENTIALS:401,CSRF_FAILED:403}[code]||400); if(st>=500)console.error(e); return json(res,st,{error:code,details:e.issues||undefined,lockedUntil:e.lockedUntil});}
});
function serveStatic(pathname,res){let reqPath=pathname; if(reqPath==='/')reqPath='/index.html'; if(reqPath==='/adminhub'||reqPath==='/adminhub/')reqPath='/adminhub/index.html'; if(reqPath==='/game'||reqPath==='/game/')reqPath='/game/index.html'; const p=safeFile(PUBLIC,reqPath); if(!p||!fs.existsSync(p)||fs.statSync(p).isDirectory())return json(res,404,{error:'NOT_FOUND'}); const ext=path.extname(p); const type={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.png':'image/png','.svg':'image/svg+xml'}[ext]||'application/octet-stream'; const data=fs.readFileSync(p); res.writeHead(200,{'content-type':type,'content-length':data.length,'cache-control':ext==='.html'?'no-store':'public,max-age=3600','x-content-type-options':'nosniff','x-frame-options':'DENY','referrer-policy':'same-origin','content-security-policy':"default-src 'self'; connect-src 'self' ws: wss:; img-src 'self' data: https:; style-src 'self' 'unsafe-inline'; script-src 'self'; frame-src 'self' data:"}); res.end(data);}
function walletView(w){return {cashBalance:w.cash_balance/100,winningsBalance:w.winnings_balance/100,lockedBalance:w.locked_balance/100,bonusBalance:w.bonus_balance/100,totalDeposited:w.total_deposited/100,totalWithdrawn:w.total_withdrawn/100};}
function depositView(d){return {...d,amount:d.amount/100};}
function withdrawView(w){return {...w,amount:w.amount/100,fee:w.fee/100};}
function parseCookie(req){const out={};for(const p of String(req.headers.cookie||'').split(';')){const i=p.indexOf('=');if(i>0)out[decodeURIComponent(p.slice(0,i).trim())]=decodeURIComponent(p.slice(i+1).trim());}return out;}
function status(code,s){return Object.assign(new Error(code),{code,status:s});}
telegram.start({approve:(kind,id,actor)=>admin.decide(kind,id,true,actor),reject:(kind,id,actor)=>admin.decide(kind,id,false,actor)});
websocket.attach(server);
server.listen(PORT,()=>console.log(`PLAY LUDU HUB v12 listening on :${PORT}`));
process.on('SIGINT',()=>{telegram.stop();server.close(()=>process.exit(0));});
process.on('SIGTERM',()=>{telegram.stop();server.close(()=>process.exit(0));});

