'use strict';
const {z}=require('zod'); const {db,getConfig,setConfig}=require('./db'); const {randomToken,sha256,hmac,timingSafeEqual,parseCookies,uid}=require('./utils'); const {audit}=require('./audit'); const wallet=require('./wallet'); const payments=require('./payments'); const pvp=require('./pvp'); const aml=require('./aml');
const PIN_LOCK=()=>Number(process.env.ADMIN_LOCK_MS||1800000), TTL=()=>Number(process.env.ADMIN_SESSION_TTL_MS||28800000);
function pin(){const p=process.env.ADMIN_PIN||''; if(process.env.NODE_ENV==='production'&&p.length<8)throw new Error('ADMIN_PIN_TOO_SHORT'); return p||'dev-admin-pin';}
function deviceHash(req,deviceId){return sha256(`${deviceId}:${req.headers['user-agent']||''}`);}
function login(req,pinAttempt,deviceId){const dh=deviceHash(req,deviceId), t=Date.now(); let d=db.prepare('SELECT * FROM admin_devices WHERE device_hash=?').get(dh); if(d?.locked_until&&d.locked_until>t)throw Object.assign(new Error('ADMIN_DEVICE_LOCKED'),{code:'ADMIN_DEVICE_LOCKED',lockedUntil:d.locked_until}); const ok=timingSafeEqual(pinAttempt,pin()); if(!ok){const n=(d?.failed_attempts||0)+1, lock=n>=3?t+PIN_LOCK():null; db.prepare('INSERT INTO admin_devices(device_hash,failed_attempts,locked_until,updated_at) VALUES(?,?,?,?) ON CONFLICT(device_hash) DO UPDATE SET failed_attempts=excluded.failed_attempts,locked_until=excluded.locked_until,updated_at=excluded.updated_at').run(dh,n,lock,t); throw Object.assign(new Error(lock?'ADMIN_DEVICE_LOCKED':'BAD_PIN'),{code:lock?'ADMIN_DEVICE_LOCKED':'BAD_PIN',lockedUntil:lock});}
  db.prepare('INSERT INTO admin_devices(device_hash,failed_attempts,locked_until,updated_at) VALUES(?,0,NULL,?) ON CONFLICT(device_hash) DO UPDATE SET failed_attempts=0,locked_until=NULL,updated_at=excluded.updated_at').run(dh,t); const id=uid('adm'), secret=randomToken(), base=`${id}.${secret}`, sig=hmac(sessionSecret(),base), token=`${base}.${sig}`, csrf=randomToken(24); db.prepare('INSERT INTO admin_sessions(id,token_hash,csrf_token,expires_at,created_at,device_hash) VALUES(?,?,?,?,?,?)').run(id,sha256(token),csrf,t+TTL(),t,dh); return {token,csrf,expiresAt:t+TTL()};}
function sessionSecret(){return process.env.SESSION_SECRET||'development-session-secret-change-me';}
function verify(req){const tok=parseCookies(req.headers.cookie||'').plh_admin; if(!tok)return null; const [id,secret,sig]=tok.split('.'); if(!id||!secret||!sig||!timingSafeEqual(hmac(sessionSecret(),`${id}.${secret}`),sig))return null; const s=db.prepare('SELECT * FROM admin_sessions WHERE id=? AND token_hash=?').get(id,sha256(tok)); return s&&s.expires_at>Date.now()?s:null;}
function csrf(req,s){if(!s||!timingSafeEqual(String(req.headers['x-csrf-token']||''),s.csrf_token))throw Object.assign(new Error('CSRF_FAILED'),{code:'CSRF_FAILED'});}
function approveAccount(id,actor='adminhub'){const u=db.prepare('SELECT * FROM users WHERE id=?').get(id); if(!u)throw err('NOT_FOUND'); if(!u.phone_verified)throw err('PHONE_NOT_VERIFIED'); if(u.status==='approved')return 'Account already approved'; if(u.status!=='pending')throw err('ACCOUNT_NOT_PENDING'); db.transaction(()=>{db.prepare("UPDATE users SET status='approved',updated_at=? WHERE id=?").run(Date.now(),id); wallet.addWelcomeBonus(id);})(); audit({actorType:'admin',actorId:actor,action:'approve_account',targetType:'user',targetId:id}); return 'Account approved';}
function rejectAccount(id,actor='adminhub'){db.prepare("UPDATE users SET status='rejected',updated_at=? WHERE id=? AND status='pending'").run(Date.now(),id); audit({actorType:'admin',actorId:actor,action:'reject_account',targetType:'user',targetId:id}); return 'Account rejected';}
async function decide(kind,id,approve,actor='adminhub'){let text; if(kind==='account')text=approve?approveAccount(id,actor):rejectAccount(id,actor); else if(kind==='deposit')text=approve?(payments.approveDeposit(id,actor),'Deposit manually verified and credited'):(payments.rejectDeposit(id,'Rejected by admin',actor),'Deposit rejected'); else if(kind==='withdrawal')text=approve?(payments.approveWithdrawal(id,actor),'Withdrawal marked paid and settled'):(payments.rejectWithdrawal(id,'Rejected by admin',actor),'Withdrawal rejected/refunded'); else if(kind==='dispute')text=resolveDispute(id,approve?'resolved':'rejected',`${approve?'Approved':'Rejected'} via ${actor}`,actor); else throw err('BAD_DECISION_KIND'); audit({actorType:'admin',actorId:actor,action:`${approve?'approve':'reject'}_${kind}`,targetType:kind,targetId:id}); return text;}
function dashboard(){return {counts:{pendingAccounts:db.prepare("SELECT COUNT(*) n FROM users WHERE status='pending'").get().n,pendingDeposits:db.prepare("SELECT COUNT(*) n FROM deposits WHERE status IN('pending','failed')").get().n,pendingWithdrawals:db.prepare("SELECT COUNT(*) n FROM withdrawals WHERE status='pending'").get().n,liveMatches:db.prepare("SELECT COUNT(*) n FROM matches WHERE status IN('active','disputed')").get().n,amlFlags:db.prepare("SELECT COUNT(*) n FROM aml_flags WHERE status='open'").get().n},config:getConfig(),admin:db.prepare("SELECT revenue_balance FROM admin_accounts WHERE id='main'").get()};}
function pending(){return {accounts:db.prepare("SELECT id,name,username,phone,email,phone_verified,created_at FROM users WHERE status='pending' AND phone_verified=1 ORDER BY created_at").all(),deposits:db.prepare("SELECT d.*,u.username FROM deposits d JOIN users u ON u.id=d.user_id WHERE d.status IN('pending','failed') ORDER BY d.created_at").all(),withdrawals:db.prepare("SELECT w.*,u.username FROM withdrawals w JOIN users u ON u.id=w.user_id WHERE w.status='pending' ORDER BY w.created_at").all(),disputes:db.prepare("SELECT d.*,m.status match_status FROM disputes d JOIN matches m ON m.id=d.match_id WHERE d.status='open' ORDER BY d.created_at").all()};}
function users(q=''){const like=`%${q}%`; return db.prepare(`SELECT u.id,u.name,u.username,u.phone,u.email,u.status,u.phone_verified,u.self_excluded,u.cool_off_until,w.* FROM users u JOIN wallets w ON w.user_id=u.id WHERE u.username LIKE ? OR u.phone LIKE ? OR u.email LIKE ? ORDER BY u.created_at DESC LIMIT 200`).all(like,like,like);}
function setUserStatus(id,status,actor){if(!['approved','rejected','banned'].includes(status))throw err('BAD_STATUS'); if(status==='approved'){const u=db.prepare('SELECT phone_verified FROM users WHERE id=?').get(id);if(!u)throw err('NOT_FOUND');if(!u.phone_verified)throw err('PHONE_NOT_VERIFIED');} db.prepare('UPDATE users SET status=?,updated_at=? WHERE id=?').run(status,Date.now(),id); audit({actorType:'admin',actorId:actor,action:'set_user_status',targetType:'user',targetId:id,details:{status}});}
function adjustBalance(id,{bucket,amount,note},actor){if(!['cash','winnings','bonus'].includes(bucket))throw err('BAD_BUCKET'); const delta=Math.round(Number(amount)*100); if(!delta)throw err('BAD_AMOUNT'); const out=wallet.adjust(id,bucket,delta,String(note||'Admin adjustment').slice(0,250)); audit({actorType:'admin',actorId:actor,action:'balance_adjustment',targetType:'user',targetId:id,details:{bucket,delta,note}}); return out;}
function saveMethod(x,actor){const schema=z.object({id:z.string().optional(),kind:z.enum(['deposit','withdrawal']),method:z.enum(['bkash','nagad','other']),label:z.string().min(1).max(80),accountNumber:z.string().min(3).max(40),enabled:z.boolean().default(true)}),v=schema.parse(x),id=v.id||uid('pm'),t=Date.now(); db.prepare('INSERT INTO payment_methods(id,kind,method,label,account_number,enabled,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET kind=excluded.kind,method=excluded.method,label=excluded.label,account_number=excluded.account_number,enabled=excluded.enabled,updated_at=excluded.updated_at').run(id,v.kind,v.method,v.label,v.accountNumber,v.enabled?1:0,t,t); audit({actorType:'admin',actorId:actor,action:'save_payment_method',targetType:'payment_method',targetId:id}); return db.prepare('SELECT * FROM payment_methods WHERE id=?').get(id);}
function ledgerRows(limit=300){return db.prepare('SELECT l.*,u.username FROM ledger l JOIN users u ON u.id=l.user_id ORDER BY l.created_at DESC LIMIT ?').all(Math.min(1000,Number(limit)||300));}
function ledgerCsv(){const rows=db.prepare('SELECT l.*,u.username FROM ledger l JOIN users u ON u.id=l.user_id ORDER BY l.created_at').all(), cols=['id','user_id','username','type','balance_bucket','amount','balance_after','ref_id','note','created_at']; const q=v=>`"${String(v??'').replace(/"/g,'""')}"`; return [cols.join(','),...rows.map(r=>cols.map(c=>q(r[c])).join(','))].join('\n');}
function resolveDispute(id,status,resolution,actor){if(!['resolved','rejected'].includes(status))throw err('BAD_DISPUTE_STATUS'); const r=db.prepare("UPDATE disputes SET status=?,resolution=?,updated_at=? WHERE id=? AND status='open'").run(status,String(resolution||'').slice(0,500),Date.now(),id); if(!r.changes)return 'Dispute already decided or not found'; audit({actorType:'admin',actorId:actor,action:'resolve_dispute',targetType:'dispute',targetId:id,details:{status,resolution}}); return `Dispute ${status}`;}
function auditRows(){return db.prepare('SELECT * FROM audit_log ORDER BY created_at DESC LIMIT 1000').all();}
async function reconciliation(date){const d=new Date(`${date}T00:00:00+06:00`),from=d.getTime(),to=from+86400000;const local={deposits:db.prepare("SELECT COUNT(*) count,COALESCE(SUM(amount),0) amount FROM deposits WHERE status='approved' AND updated_at>=? AND updated_at<?").get(from,to),withdrawals:db.prepare("SELECT COUNT(*) count,COALESCE(SUM(amount-fee),0) amount FROM withdrawals WHERE status='paid' AND updated_at>=? AND updated_at<?").get(from,to),ledgerDeposits:db.prepare("SELECT COALESCE(SUM(amount),0) amount FROM ledger WHERE type='deposit' AND balance_bucket='cash' AND created_at>=? AND created_at<?").get(from,to),ledgerWithdrawals:db.prepare("SELECT COALESCE(-SUM(amount),0) amount FROM ledger WHERE type='withdraw_paid' AND balance_bucket='locked' AND created_at>=? AND created_at<?").get(from,to)};return{date,mode:'manual',local,checks:{depositLedgerMatches:local.deposits.amount===local.ledgerDeposits.amount,withdrawLedgerMatches:local.withdrawals.amount===local.ledgerWithdrawals.amount}};}
function err(code){return Object.assign(new Error(code),{code});}
module.exports={login,verify,csrf,decide,approveAccount,rejectAccount,resolveDispute,dashboard,pending,users,setUserStatus,adjustBalance,saveMethod,ledgerRows,ledgerCsv,auditRows,reconciliation,getConfig,setConfig,pvp,aml};

