'use strict';
const {db,getConfig}=require('./db'); const {uid}=require('./utils');
function dayStart(t=Date.now()){const off=6*3600000,day=86400000; return Math.floor((t+off)/day)*day-off;}
function sumToday(table,userId,statuses){const marks=statuses.map(()=>'?').join(','); return db.prepare(`SELECT COALESCE(SUM(amount),0) total FROM ${table} WHERE user_id=? AND created_at>=? AND status IN (${marks})`).get(userId,dayStart(),...statuses).total;}
function flag(userId,kind,severity,refId,details){db.prepare('INSERT INTO aml_flags(id,user_id,kind,severity,ref_id,details,created_at) VALUES(?,?,?,?,?,?,?)').run(uid('aml'),userId,kind,severity,refId,JSON.stringify(details),Date.now());}
function checkDeposit(userId,amount,refId=null){const c=getConfig(); const daily=sumToday('deposits',userId,['pending','approved']); const user=db.prepare('SELECT daily_deposit_limit,self_excluded,cool_off_until FROM users WHERE id=?').get(userId); if(user.self_excluded)throw Object.assign(new Error('SELF_EXCLUDED'),{code:'SELF_EXCLUDED'}); if(user.cool_off_until&&user.cool_off_until>Date.now())throw Object.assign(new Error('COOL_OFF_ACTIVE'),{code:'COOL_OFF_ACTIVE'}); const limit=Math.round(Number(user.daily_deposit_limit??c.dailyDepositLimit)*100); if(daily+amount>limit)throw Object.assign(new Error('DAILY_DEPOSIT_LIMIT'),{code:'DAILY_DEPOSIT_LIMIT'}); const threshold=Math.round(Number(c.amlThreshold)*100); if(amount>=threshold)flag(userId,'deposit_threshold','high',refId,{amount,threshold}); const lastHour=Date.now()-3600000; const count=db.prepare('SELECT COUNT(*) n FROM deposits WHERE user_id=? AND created_at>=?').get(userId,lastHour).n; if(count>=4)flag(userId,'deposit_velocity','medium',refId,{countLastHour:count});}
function checkWithdrawal(userId,amount,refId=null){const c=getConfig(); const daily=sumToday('withdrawals',userId,['pending','processing','paid']); const limit=Math.round(Number(c.dailyWithdrawLimit)*100); if(daily+amount>limit)throw Object.assign(new Error('DAILY_WITHDRAW_LIMIT'),{code:'DAILY_WITHDRAW_LIMIT'}); const threshold=Math.round(Number(c.amlThreshold)*100); if(amount>=threshold)flag(userId,'withdraw_threshold','high',refId,{amount,threshold});}
function report(){return db.prepare(`SELECT a.*,u.username,u.phone FROM aml_flags a JOIN users u ON u.id=a.user_id WHERE a.status='open' ORDER BY a.created_at DESC LIMIT 500`).all();}
module.exports={checkDeposit,checkWithdrawal,flag,report};

