'use strict';
const crypto=require('crypto'); const {db}=require('./db'); const {uid}=require('./utils');
function key(){const raw=process.env.KYC_STORAGE_KEY||''; if(!/^[a-f0-9]{64}$/i.test(raw)){if(process.env.NODE_ENV==='production')throw new Error('KYC_STORAGE_KEY_REQUIRED'); return crypto.createHash('sha256').update('development-only-kyc-key').digest();} return Buffer.from(raw,'hex');}
function upload(userId,{docType,mimeType,dataBase64}){if(!['nid','passport'].includes(docType))throw err('INVALID_DOC_TYPE'); if(!['image/jpeg','image/png','application/pdf'].includes(mimeType))throw err('INVALID_MIME'); const plain=Buffer.from(dataBase64,'base64'); if(!plain.length||plain.length>2*1024*1024)throw err('KYC_SIZE_LIMIT'); const iv=crypto.randomBytes(12), cipher=crypto.createCipheriv('aes-256-gcm',key(),iv); const enc=Buffer.concat([cipher.update(plain),cipher.final()]),tag=cipher.getAuthTag(),id=uid('kyc'); db.transaction(()=>{db.prepare('INSERT INTO kyc_documents(id,user_id,doc_type,mime_type,file_name,cipher_blob,iv,auth_tag,created_at) VALUES(?,?,?,?,?,?,?,?,?)').run(id,userId,docType,mimeType,`${id}.${mimeType==='application/pdf'?'pdf':mimeType.endsWith('png')?'png':'jpg'}`,enc,iv,tag,Date.now()); db.prepare("UPDATE users SET kyc_status='pending',updated_at=? WHERE id=?").run(Date.now(),userId);})(); return {id,status:'pending'};}
function read(id){const row=db.prepare('SELECT * FROM kyc_documents WHERE id=?').get(id); if(!row)throw err('NOT_FOUND'); const decipher=crypto.createDecipheriv('aes-256-gcm',key(),row.iv); decipher.setAuthTag(row.auth_tag); const plain=Buffer.concat([decipher.update(row.cipher_blob),decipher.final()]); return {id:row.id,userId:row.user_id,docType:row.doc_type,mimeType:row.mime_type,status:row.status,dataBase64:plain.toString('base64')};}
function review(id,status){if(!['verified','rejected'].includes(status))throw err('INVALID_STATUS'); const row=db.prepare('SELECT * FROM kyc_documents WHERE id=?').get(id); if(!row)throw err('NOT_FOUND'); db.transaction(()=>{db.prepare('UPDATE kyc_documents SET status=?,reviewed_at=? WHERE id=?').run(status,Date.now(),id); db.prepare('UPDATE users SET kyc_status=?,updated_at=? WHERE id=?').run(status,Date.now(),row.user_id);})(); return {id,status,userId:row.user_id};}
function err(code){return Object.assign(new Error(code),{code});}
module.exports={upload,read,review};

