'use strict';
const crypto=require('crypto'); const {db,getConfig}=require('./db'); const wallet=require('./wallet'); const aml=require('./aml'); const {uid,hmac,timingSafeEqual}=require('./utils');
function cfg(){return {base:(process.env.PAYMENT_GATEWAY_BASE_URL||'').replace(/\/$/,''),key:process.env.PAYMENT_GATEWAY_API_KEY||'',secret:process.env.PAYMENT_GATEWAY_SECRET||'',verifyPath:process.env.PAYMENT_VERIFY_PATH||'/v1/deposits/verify',payoutPath:process.env.PAYMENT_PAYOUT_PATH||'/v1/payouts',reconPath:process.env.PAYMENT_RECONCILIATION_PATH||'/v1/reconciliation/daily'};}
async function gateway(path,payload,idempotencyKey){const c=cfg(); if(!c.base||!c.key||!c.secret)throw err('GATEWAY_NOT_CONFIGURED'); const body=JSON.stringify(payload), ts=String(Date.now()), sig=hmac(c.secret,`${ts}.${body}`); const r=await fetch(`${c.base}${path}`,{method:'POST',headers:{'content-type':'application/json','authorization':`Bearer ${c.key}`,'x-signature':sig,'x-timestamp':ts,'idempotency-key':idempotencyKey},body,signal:AbortSignal.timeout(15000)}); const text=await r.text(); let data={}; try{data=JSON.parse(text)}catch{data={raw:text}} if(!r.ok)throw Object.assign(new Error('GATEWAY_ERROR'),{code:'GATEWAY_ERROR',status:r.status,data}); return data;}
function createDeposit(userId,{method,amount,transactionId}){const c=getConfig(), paisa=Math.round(Number(amount)*100); if(!['bkash','nagad'].includes(method))throw err('INVALID_METHOD'); if(paisa<Math.round(c.minDeposit*100)||paisa>Math.round(c.maxDeposit*100))throw err('DEPOSIT_LIMIT'); const id=uid('dep'); aml.checkDeposit(userId,paisa,id); db.prepare('INSERT INTO deposits(id,user_id,method,amount,transaction_id,created_at,updated_at) VALUES(?,?,?,?,?,?,?)').run(id,userId,method,paisa,String(transactionId).trim(),Date.now(),Date.now()); return getDeposit(id);}
function getDeposit(id){return db.prepare('SELECT * FROM deposits WHERE id=?').get(id);}
async function approveDeposit(id){const d=getDeposit(id); if(!d)throw err('NOT_FOUND'); if(!['pending','failed'].includes(d.status))return d; let vr; try{vr=await gateway(cfg().verifyPath,{method:d.method,amount:d.amount/100,transactionId:d.transaction_id,reference:id},`verify:${id}`);}catch(e){db.prepare("UPDATE deposits SET status='failed',admin_note=?,updated_at=? WHERE id=?").run(JSON.stringify(e.data||{code:e.code}),Date.now(),id); throw e;} if(vr.verified!==true && vr.status!=='verified' && vr.status!=='success')throw err('DEPOSIT_NOT_VERIFIED'); if(vr.amount!=null&&Math.round(Number(vr.amount)*100)!==d.amount)throw err('DEPOSIT_AMOUNT_MISMATCH'); if(vr.transactionId!=null&&String(vr.transactionId)!==d.transaction_id)throw err('DEPOSIT_TRANSACTION_MISMATCH'); db.transaction(()=>{const latest=getDeposit(id); if(latest.status!=='pending'&&latest.status!=='failed')return; wallet.creditDeposit(d.user_id,d.amount,id); db.prepare("UPDATE deposits SET status='approved',gateway_ref=?,updated_at=? WHERE id=?").run(String(vr.reference||vr.id||d.transaction_id),Date.now(),id);})(); return getDeposit(id);}
function rejectDeposit(id,note='Rejected by admin'){const d=getDeposit(id); if(!d)throw err('NOT_FOUND'); if(d.status==='pending'||d.status==='failed')db.prepare("UPDATE deposits SET status='rejected',admin_note=?,updated_at=? WHERE id=?").run(note,Date.now(),id); return getDeposit(id);}
function createWithdrawal(userId,{method,accountNumber,amount,sourceBucket='winnings'}){const c=getConfig(), paisa=Math.round(Number(amount)*100); if(!['bkash','nagad'].includes(method))throw err('INVALID_METHOD'); if(sourceBucket==='cash'&&!c.withdrawFromCash)throw err('CASH_WITHDRAW_DISABLED'); if(sourceBucket==='bonus'&&!c.bonusWithdrawable)throw err('BONUS_WITHDRAW_DISABLED'); if(!['winnings','cash','bonus'].includes(sourceBucket))throw err('INVALID_SOURCE'); if(paisa<Math.round(c.minWithdraw*100)||paisa>Math.round(c.maxWithdraw*100))throw err('WITHDRAW_LIMIT'); const u=db.prepare('SELECT kyc_status,self_excluded FROM users WHERE id=?').get(userId); if(c.kycRequired&&u.kyc_status!=='verified')throw err('KYC_REQUIRED'); if(u.self_excluded)throw err('SELF_EXCLUDED'); aml.checkWithdrawal(userId,paisa); const fee=Math.round(paisa*(Number(c.withdrawalFeePercent||0)/100)), id=uid('wd'); db.transaction(()=>{wallet.lockWithdrawal(userId,paisa,sourceBucket,id); db.prepare('INSERT INTO withdrawals(id,user_id,method,account_number,amount,fee,source_bucket,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?)').run(id,userId,method,String(accountNumber).trim(),paisa,fee,sourceBucket,Date.now(),Date.now());})(); return getWithdrawal(id);}
function getWithdrawal(id){return db.prepare('SELECT * FROM withdrawals WHERE id=?').get(id);}
async function approveWithdrawal(id){const w=getWithdrawal(id); if(!w)throw err('NOT_FOUND'); if(w.status!=='pending')return w; db.prepare("UPDATE withdrawals SET status='processing',updated_at=? WHERE id=?").run(Date.now(),id); try{const r=await gateway(cfg().payoutPath,{method:w.method,accountNumber:w.account_number,amount:(w.amount-w.fee)/100,fee:w.fee/100,reference:id},`payout:${id}`); db.prepare('UPDATE withdrawals SET gateway_ref=?,updated_at=? WHERE id=?').run(String(r.reference||r.id||''),Date.now(),id); if(r.status==='paid'||r.status==='completed')confirmWithdrawalPaid(id,String(r.reference||r.id||'')); return getWithdrawal(id);}catch(e){db.prepare("UPDATE withdrawals SET admin_note=?,updated_at=? WHERE id=?").run(`Payout submission uncertain: ${e.code||e.message}`,Date.now(),id); throw Object.assign(e,{code:e.code||'PAYOUT_SUBMISSION_UNCERTAIN'});}}
function confirmWithdrawalPaid(id,gatewayRef=null){db.transaction(()=>{const w=getWithdrawal(id); if(!w||w.status==='paid')return; if(!['processing','pending'].includes(w.status))throw err('INVALID_WITHDRAW_STATUS'); wallet.finalizeWithdrawal(w.user_id,w.amount,w.fee,id); db.prepare("UPDATE withdrawals SET status='paid',gateway_ref=COALESCE(?,gateway_ref),updated_at=? WHERE id=?").run(gatewayRef,Date.now(),id);})();}
function failWithdrawal(id,note='Payout failed'){db.transaction(()=>{const w=getWithdrawal(id); if(!w||['failed','rejected','paid'].includes(w.status))return; wallet.refundWithdrawal(w.user_id,w.amount,w.source_bucket,id,note); db.prepare("UPDATE withdrawals SET status='failed',admin_note=?,updated_at=? WHERE id=?").run(note,Date.now(),id);})(); return getWithdrawal(id);}
function rejectWithdrawal(id,note='Rejected by admin'){db.transaction(()=>{const w=getWithdrawal(id); if(!w)throw err('NOT_FOUND'); if(w.status!=='pending')return; wallet.refundWithdrawal(w.user_id,w.amount,w.source_bucket,id,note); db.prepare("UPDATE withdrawals SET status='rejected',admin_note=?,updated_at=? WHERE id=?").run(note,Date.now(),id);})(); return getWithdrawal(id);}
function verifyWebhook(rawBody,signature){const sec=process.env.PAYMENT_WEBHOOK_SECRET||''; if(!sec)throw err('WEBHOOK_SECRET_NOT_CONFIGURED'); return timingSafeEqual(hmac(sec,rawBody),String(signature||''));}
function processWebhook(rawBody,signature){if(!verifyWebhook(rawBody,signature))throw err('BAD_WEBHOOK_SIGNATURE'); const event=JSON.parse(rawBody), eventId=String(event.id||event.eventId||''); if(!eventId)throw err('WEBHOOK_ID_REQUIRED'); const ph=crypto.createHash('sha256').update(rawBody).digest('hex'); const exists=db.prepare('SELECT payload_hash FROM gateway_events WHERE event_id=?').get(eventId); if(exists){if(exists.payload_hash!==ph)throw err('WEBHOOK_ID_REUSE'); return {duplicate:true};} db.transaction(()=>{db.prepare('INSERT INTO gateway_events(event_id,event_type,payload_hash,processed_at) VALUES(?,?,?,?)').run(eventId,String(event.type||'unknown'),ph,Date.now()); if(event.type==='payout.paid')confirmWithdrawalPaid(String(event.reference||event.withdrawalId),String(event.gatewayRef||'')); if(event.type==='payout.failed')failWithdrawal(String(event.reference||event.withdrawalId),'Gateway webhook failure');})(); return {ok:true};}
async function gatewayReconciliation(date){const c=cfg(); try{return await gateway(c.reconPath,{date},`reconcile:${date}`);}catch(e){return {error:e.code||e.message,details:e.data||null};}}
function err(code){return Object.assign(new Error(code),{code});}
module.exports={createDeposit,approveDeposit,rejectDeposit,getDeposit,createWithdrawal,approveWithdrawal,rejectWithdrawal,failWithdrawal,confirmWithdrawalPaid,getWithdrawal,processWebhook,gatewayReconciliation};

