'use strict';
let handlers={}; let offset=0; let running=false;
const token=()=>process.env.TELEGRAM_BOT_TOKEN||''; const chatId=()=>process.env.TELEGRAM_CHAT_ID||'';
const admins=()=>new Set(String(process.env.TELEGRAM_ADMIN_IDS||'').split(',').map(x=>x.trim()).filter(Boolean));
async function api(method,payload){if(!token())return null; const r=await fetch(`https://api.telegram.org/bot${token()}/${method}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload),signal:AbortSignal.timeout(20000)}); const data=await r.json(); if(!data.ok)throw new Error(`TELEGRAM_${method}:${data.description||'error'}`); return data.result;}
async function notify(kind,obj){if(!token()||!chatId())return; const m=message(kind,obj); if(!m)return; await api('sendMessage',{chat_id:chatId(),text:m.text,parse_mode:'HTML',reply_markup:{inline_keyboard:[[...m.buttons.map(b=>({text:b.text,callback_data:b.data}))]]}}).catch(e=>console.error(e.message));}
function esc(v){return String(v??'').replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]));}
function message(kind,o){if(kind==='account')return{text:`👤 <b>Account approval</b>\nUser: ${esc(o.username)}\nPhone: ${esc(o.phone)}\nEmail: ${esc(o.email)}`,buttons:[{text:'✅ Approve',data:`a:account:${o.id}`},{text:'❌ Reject',data:`r:account:${o.id}`} ]}; if(kind==='deposit')return{text:`💰 <b>Deposit</b>\nUser: ${esc(o.username||o.user_id)}\nMethod: ${esc(o.method)}\nAmount: ৳${(o.amount/100).toFixed(2)}\nTxn: ${esc(o.transaction_id)}`,buttons:[{text:'✅ Approve',data:`a:deposit:${o.id}`},{text:'❌ Reject',data:`r:deposit:${o.id}`}]}; if(kind==='withdrawal')return{text:`🏧 <b>Withdrawal</b>\nUser: ${esc(o.username||o.user_id)}\nMethod: ${esc(o.method)}\nAmount: ৳${(o.amount/100).toFixed(2)}\nAccount: ${esc(o.account_number)}`,buttons:[{text:'✅ Approve',data:`a:withdrawal:${o.id}`},{text:'❌ Reject',data:`r:withdrawal:${o.id}`}]}; if(kind==='dispute')return{text:`⚠️ <b>Dispute</b>\nMatch: ${esc(o.matchId)}\nReason: ${esc(o.reason)}`,buttons:[{text:'✅ Resolve',data:`a:dispute:${o.id}`},{text:'❌ Reject',data:`r:dispute:${o.id}`}]}; return null;}
async function poll(){while(running&&token()){try{const result=await api('getUpdates',{offset,timeout:25,allowed_updates:['callback_query']})||[]; for(const u of result){offset=Math.max(offset,u.update_id+1); if(u.callback_query)await callback(u.callback_query);}}catch(e){console.error('telegram poll',e.message); await new Promise(r=>setTimeout(r,3000));}}}
async function callback(q){const from=String(q.from?.id||''); if(!admins().has(from)){await api('answerCallbackQuery',{callback_query_id:q.id,text:'Not authorized',show_alert:true});return;} const [action,kind,id]=String(q.data||'').split(':'); if(!['a','r'].includes(action)||!kind||!id)return; try{const fn=action==='a'?handlers.approve:handlers.reject; if(!fn)throw new Error('HANDLER_NOT_READY'); const text=await fn(kind,id,`telegram:${from}`); await api('answerCallbackQuery',{callback_query_id:q.id,text:'Done'}); if(q.message)await api('editMessageText',{chat_id:q.message.chat.id,message_id:q.message.message_id,text:`${q.message.text}\n\n✅ ${action==='a'?'Approved':'Rejected'} by ${from}\n${text||''}`});}catch(e){await api('answerCallbackQuery',{callback_query_id:q.id,text:e.code||e.message,show_alert:true}).catch(()=>{});}}
function start(h){handlers=h||{}; if(running||!token())return; running=true; poll();}
function stop(){running=false;}
module.exports={start,stop,notify,api};

