import './admin.css';

const root=document.querySelector<HTMLDivElement>('#root');
if(!root)throw new Error('ROOT_NOT_FOUND');

root.innerHTML=`
<section id="adminLogin" class="gate">
  <div class="gate-card">
    <div class="shield">◆</div>
    <div class="eyebrow">PRIVATE OPERATOR ROUTE</div>
    <h1>Admin Hub</h1>
    <p class="muted">Server-side PIN verification. Three failed attempts lock this browser/device identity for 30 minutes.</p>
    <form id="adminLoginForm">
      <label>Admin PIN</label>
      <div class="pin-row">
        <input type="password" name="pin" autocomplete="off" maxlength="128" placeholder="Enter private PIN" required>
        <button type="submit">UNLOCK</button>
      </div>
    </form>
    <div class="gate-status">Manual payments • Ledger • PvP • AML • Audit</div>
    <a class="back-link" href="/">← Main player site</a>
  </div>
</section>

<section id="adminApp" class="admin-app hidden">
  <header class="topbar">
    <div class="brand"><span>◆</span><div><b>PLAY LUDU HUB</b><small>ADMIN CONTROL CENTER</small></div></div>
    <div class="top-actions"><span>Secure server session</span><a href="/">Player site</a></div>
  </header>
  <main class="shell">
    <nav class="adminnav" id="nav">
      <button data-tab="dashboard">Dashboard</button>
      <button data-tab="pending">Pending</button>
      <button data-tab="users">Users</button>
      <button data-tab="matches">Live Matches</button>
      <button data-tab="payments">Payment Methods</button>
      <button data-tab="config">Config</button>
      <button data-tab="ledger">Ledger</button>
      <button data-tab="aml">AML</button>
      <button data-tab="audit">Audit</button>
      <button data-tab="recon">Reconciliation</button>
    </nav>
    <section id="view"></section>
  </main>
</section>

<div id="toast" class="toast hidden"></div>
<div id="modal" class="modal hidden"><div class="modal-card"><button id="closeModal" class="secondary">Close</button><div id="modalBody"></div></div></div>`;


type Obj=Record<string,any>;
const $=<T extends Element=HTMLElement>(s:string)=>document.querySelector<T>(s);
let csrf=sessionStorage.getItem('plh_admin_csrf')||'';
const esc=(v:any)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'} as Obj)[c]);
const money=(v:any)=>'৳'+(Number(v||0)/100).toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2});
async function adminApi(path:string,opts:Obj={}){const o:any={...opts,headers:{...(opts.headers||{})}};if(csrf)o.headers['x-csrf-token']=csrf;if(o.body&&typeof o.body!=='string'){o.headers['content-type']='application/json';o.body=JSON.stringify(o.body)}const r=await fetch(path,o),d=await r.json().catch(()=>({}));if(!r.ok)throw Object.assign(new Error(d.error||'REQUEST_FAILED'),{data:d,status:r.status});return d}
function toast(m:string,bad=false){const t=$('#toast');if(!t)return;t.textContent=m;t.className='toast '+(bad?'bad':'ok');setTimeout(()=>t.className='toast hidden',3200)}
function format(c:string,v:any){if(c.endsWith('_at')||c.endsWith('At'))return v?esc(new Date(Number(v)).toLocaleString()):'—';if(['amount','balance_after','cash_balance','winnings_balance','locked_balance','bonus_balance'].includes(c)&&Number.isFinite(Number(v)))return money(v);return esc(typeof v==='object'?JSON.stringify(v):v)}
function table(cols:string[],rows:any[],action?:(r:any)=>string){return '<div class="table"><table><thead><tr>'+cols.map(c=>'<th>'+esc(c.replaceAll('_',' '))+'</th>').join('')+(action?'<th>Actions</th>':'')+'</tr></thead><tbody>'+(rows.length?rows.map(r=>'<tr>'+cols.map(c=>'<td>'+format(c,r[c])+'</td>').join('')+(action?'<td>'+action(r)+'</td>':'')+'</tr>').join(''):'<tr><td colspan="'+(cols.length+(action?1:0))+'"><div class="empty-admin">No records</div></td></tr>')+'</tbody></table></div>'}
async function decision(kind:string,id:string,approve:boolean){return adminApi('/api/admin/'+kind+'/'+encodeURIComponent(id)+'/'+(approve?'approve':'reject'),{method:'POST',headers:{'idempotency-key':crypto.randomUUID()}})}
function actions(kind:string,id:string){const yes=kind==='deposit'?'Verify':kind==='withdrawal'?'Mark paid':'Approve';return '<div class="actions"><button data-decision="'+kind+':'+id+':1">'+yes+'</button><button data-decision="'+kind+':'+id+':0" class="danger">Reject</button></div>'}
function bindDecision(refresh:()=>void){document.querySelectorAll<HTMLButtonElement>('[data-decision]').forEach(b=>b.onclick=async()=>{const parts=String(b.dataset.decision).split(':'),old=b.textContent||'';b.disabled=true;b.textContent='Working…';try{await decision(parts[0],parts[1],parts[2]==='1');toast('Decision saved');refresh()}catch(x:any){b.disabled=false;b.textContent=old;toast(x.message,true)}})}
async function login(ev:SubmitEvent){ev.preventDefault();const form=ev.currentTarget as HTMLFormElement,b=ev.submitter as HTMLButtonElement,fd=new FormData(form);b.disabled=true;b.textContent='UNLOCKING…';try{const r=await adminApi('/api/admin/login',{method:'POST',body:{pin:fd.get('pin')}});csrf=r.csrf;sessionStorage.setItem('plh_admin_csrf',csrf);await showApp()}catch(x:any){b.disabled=false;b.textContent='UNLOCK';toast(x.data?.lockedUntil?'Locked until '+new Date(x.data.lockedUntil).toLocaleString():x.message,true)}}
async function showApp(){try{await adminApi('/api/admin/dashboard');$('#adminLogin')?.classList.add('hidden');$('#adminApp')?.classList.remove('hidden');openTab('dashboard')}catch{$('#adminLogin')?.classList.remove('hidden');$('#adminApp')?.classList.add('hidden')}}
async function openTab(tab:string){document.querySelectorAll<HTMLElement>('#nav [data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));try{if(tab==='dashboard')await dashboard();else if(tab==='pending')await pending();else if(tab==='users')await users();else if(tab==='matches')await matches();else if(tab==='payments')await methods();else if(tab==='config')await config();else if(tab==='ledger')await ledger();else if(tab==='aml')await aml();else if(tab==='audit')await audit();else if(tab==='recon')await recon()}catch(x:any){toast(x.message,true)}}
async function dashboard(){const r=await adminApi('/api/admin/dashboard'),c=r.counts||{},v=$('#view');if(!v)return;const cards=Object.entries(c).map(([k,val])=>'<article class="metric-card"><span>'+esc(k.replace(/([A-Z])/g,' $1'))+'</span><b>'+esc(val)+'</b></article>').join('');v.innerHTML='<section class="admin-title"><div><span>OPERATIONS OVERVIEW</span><h1>Dashboard</h1><p>Live platform health and pending work.</p></div><b>SECURE SESSION</b></section><div class="metrics">'+cards+'<article class="metric-card revenue"><span>Admin revenue</span><b>'+money(r.admin?.revenue_balance)+'</b></article></div>'}
async function pending(){const r=await adminApi('/api/admin/pending'),v=$('#view');if(!v)return;v.innerHTML='<section class="admin-title"><div><span>QUEUE</span><h1>Pending approvals</h1><p>Review accounts, deposits, withdrawals and disputes.</p></div></section><div class="card"><h2>Accounts</h2>'+table(['username','phone','email','created_at'],r.accounts||[],x=>actions('account',x.id))+'</div><div class="card"><h2>Deposits</h2>'+table(['username','method','amount','transaction_id','status'],r.deposits||[],x=>actions('deposit',x.id))+'</div><div class="card"><h2>Withdrawals</h2>'+table(['username','method','amount','account_number'],r.withdrawals||[],x=>actions('withdrawal',x.id))+'</div><div class="card"><h2>Open disputes</h2>'+table(['id','match_id','match_status','reason','created_at'],r.disputes||[],x=>'<div class="actions"><button data-dispute="'+x.id+'" data-dstatus="resolve">Resolve</button><button data-dispute="'+x.id+'" data-dstatus="reject" class="danger">Reject</button></div>')+'</div>';bindDecision(pending);document.querySelectorAll<HTMLButtonElement>('[data-dispute]').forEach(b=>b.onclick=()=>resolveDispute(String(b.dataset.dispute),String(b.dataset.dstatus)))}
async function users(){const r=await adminApi('/api/admin/users'),v=$('#view');if(!v)return;v.innerHTML='<section class="admin-title"><div><span>PLAYER MANAGEMENT</span><h1>Users</h1><p>Account status and wallet controls.</p></div></section><div class="card">'+table(['username','phone','status','cash_balance','winnings_balance','locked_balance'],r.items||[],x=>'<div class="actions"><button data-adjust="'+x.id+'">Adjust</button><button data-ban="'+x.id+'" class="danger">Ban</button></div>')+'</div>';document.querySelectorAll<HTMLButtonElement>('[data-ban]').forEach(b=>b.onclick=()=>setStatus(String(b.dataset.ban),'banned'));document.querySelectorAll<HTMLButtonElement>('[data-adjust]').forEach(b=>b.onclick=()=>adjust(String(b.dataset.adjust)))}
async function setStatus(id:string,status:string){try{await adminApi('/api/admin/users/'+encodeURIComponent(id)+'/status',{method:'POST',body:{status}});toast('Status updated');users()}catch(x:any){toast(x.message,true)}}
async function adjust(id:string){const bucket=prompt('Bucket: cash, winnings, bonus','cash');if(!bucket)return;const amount=Number(prompt('Amount in taka (negative allowed)','0'));if(!amount)return;const note=prompt('Audit note','Admin adjustment');try{await adminApi('/api/admin/users/'+encodeURIComponent(id)+'/adjust',{method:'POST',headers:{'idempotency-key':crypto.randomUUID()},body:{bucket,amount,note}});toast('Balance adjusted');users()}catch(x:any){toast(x.message,true)}}
async function matches(){const r=await adminApi('/api/admin/live-matches'),items=r.items||[],v=$('#view');if(!v)return;(window as any).__liveMatches=items;v.innerHTML='<section class="admin-title"><div><span>REAL-TIME PVP</span><h1>Live matches</h1><p>Observe active/disputed tables and settle exceptional cases.</p></div></section><div class="card">'+table(['id','status','playerAId','playerBId','entryFee','betAmount','startedAt'],items,x=>'<div class="actions"><button data-watch="'+x.id+'" class="secondary">Inspect</button><button data-force="'+x.id+'">Force end</button></div>')+'</div>';document.querySelectorAll<HTMLButtonElement>('[data-watch]').forEach(b=>b.onclick=()=>{const m=items.find((x:any)=>x.id===b.dataset.watch),body=$('#modalBody');if(body)body.innerHTML='<h3>'+esc(m?.id)+'</h3><pre class="json">'+esc(JSON.stringify(m?.state,null,2))+'</pre>';$('#modal')?.classList.remove('hidden')});document.querySelectorAll<HTMLButtonElement>('[data-force]').forEach(b=>b.onclick=async()=>{const winnerId=prompt('Winner user ID');if(!winnerId)return;const reason=prompt('Reason','admin_force_end');try{await adminApi('/api/admin/matches/'+encodeURIComponent(String(b.dataset.force))+'/force-end',{method:'POST',headers:{'idempotency-key':crypto.randomUUID()},body:{winnerId,reason}});toast('Match settled');matches()}catch(x:any){toast(x.message,true)}})}
async function methods(){const r=await adminApi('/api/admin/payment-methods'),items=r.items||[],v=$('#view');if(!v)return;const dep=items.filter((x:any)=>x.enabled&&x.kind==='deposit').length,wd=items.filter((x:any)=>x.enabled&&x.kind==='withdrawal').length;v.innerHTML='<section class="admin-title"><div><span>PLAYER WALLET SYNC</span><h1>Payment methods</h1><p>Enabled methods appear immediately in the player wallet.</p></div><div class="sync"><b>'+dep+' deposit live</b><b>'+wd+' withdrawal live</b></div></section><div class="card"><form id="methodForm" class="method-form"><label><span>Show in</span><select name="kind"><option value="deposit">Deposit</option><option value="withdrawal">Withdrawal</option></select></label><label><span>Wallet</span><select name="method"><option value="bkash">bKash</option><option value="nagad">Nagad</option></select></label><label><span>Label</span><input name="label" placeholder="bKash Send Money" required></label><label><span>Number / account</span><input name="accountNumber" placeholder="01XXXXXXXXX" required></label><label class="toggle"><input type="checkbox" name="enabled" checked><i></i><span>Visible</span></label><button>Save method</button></form><div class="method-list">'+(items.length?items.map((x:any)=>'<article class="method-row '+(x.enabled?'live':'off')+'"><div class="method-mark '+esc(x.method)+'">'+(x.method==='bkash'?'bK':'N')+'</div><div><span>'+esc(x.kind)+' • '+(x.enabled?'LIVE':'HIDDEN')+'</span><b>'+esc(x.label)+'</b><small>'+esc(x.account_number)+'</small></div><div class="actions"><button data-edit="'+x.id+'">Edit</button><button data-toggle="'+x.id+'" class="'+(x.enabled?'danger':'secondary')+'">'+(x.enabled?'Hide':'Enable')+'</button></div></article>').join(''):'<div class="empty-admin">No payment methods</div>')+'</div></div>';document.querySelector<HTMLFormElement>('#methodForm')?.addEventListener('submit',async ev=>{ev.preventDefault();const fd=new FormData(ev.currentTarget),b=ev.submitter as HTMLButtonElement;b.disabled=true;try{await adminApi('/api/admin/payment-methods',{method:'POST',body:{kind:fd.get('kind'),method:fd.get('method'),label:fd.get('label'),accountNumber:fd.get('accountNumber'),enabled:fd.get('enabled')==='on'}});toast('Payment method saved');methods()}catch(x:any){b.disabled=false;toast(x.message,true)}});document.querySelectorAll<HTMLButtonElement>('[data-edit]').forEach(b=>b.onclick=()=>editMethod(items.find((x:any)=>x.id===b.dataset.edit)));document.querySelectorAll<HTMLButtonElement>('[data-toggle]').forEach(b=>b.onclick=()=>toggleMethod(items.find((x:any)=>x.id===b.dataset.toggle)))}
async function editMethod(x:any){const label=prompt('Label',x.label);if(label==null)return;const accountNumber=prompt('Merchant/account number',x.account_number);if(accountNumber==null)return;try{await adminApi('/api/admin/payment-methods',{method:'POST',body:{id:x.id,kind:x.kind,method:x.method,label,accountNumber,enabled:!!x.enabled}});toast('Updated');methods()}catch(e:any){toast(e.message,true)}}
async function toggleMethod(x:any){try{await adminApi('/api/admin/payment-methods',{method:'POST',body:{id:x.id,kind:x.kind,method:x.method,label:x.label,accountNumber:x.account_number,enabled:!x.enabled}});toast(x.enabled?'Hidden from players':'Enabled for players');methods()}catch(e:any){toast(e.message,true)}}
async function config(){const r=await adminApi('/api/admin/dashboard'),c=r.config||{},v=$('#view');if(!v)return;v.innerHTML='<section class="admin-title"><div><span>SYSTEM RULES</span><h1>Configuration</h1><p>Server-side match, wallet and safety settings.</p></div></section><div class="card"><form id="configForm" class="config-grid">'+Object.entries(c).map(([k,val])=>'<label><span>'+esc(k)+'</span>'+(typeof val==='boolean'?'<select name="'+esc(k)+'"><option value="true" '+(val?'selected':'')+'>true</option><option value="false" '+(!val?'selected':'')+'>false</option></select>':'<input name="'+esc(k)+'" value="'+esc(val)+'">')+'</label>').join('')+'<button>Save configuration</button></form></div>';document.querySelector<HTMLFormElement>('#configForm')?.addEventListener('submit',async ev=>{ev.preventDefault();const out:Obj={};for(const [k,v] of new FormData(ev.currentTarget)){const s=String(v);if(s==='true'||s==='false')out[k]=s==='true';else if(s!==''&&!Number.isNaN(Number(s)))out[k]=Number(s);else out[k]=s}try{await adminApi('/api/admin/config',{method:'POST',body:out});toast('Configuration saved');config()}catch(x:any){toast(x.message,true)}})}
async function ledger(){const r=await adminApi('/api/admin/ledger?limit=500'),v=$('#view');if(v)v.innerHTML='<section class="admin-title"><div><span>FINANCIAL HISTORY</span><h1>Ledger</h1><p>Immutable wallet movement records.</p></div><a class="export" href="/api/admin/ledger.csv" target="_blank">Export CSV</a></section><div class="card">'+table(['created_at','username','type','balance_bucket','amount','balance_after','ref_id'],r.items||[])+'</div>'}
async function aml(){const r=await adminApi('/api/admin/aml'),v=$('#view');if(v)v.innerHTML='<section class="admin-title"><div><span>RISK CONTROL</span><h1>AML flags</h1><p>Open monitoring flags requiring review.</p></div></section><div class="card">'+table(['created_at','username','kind','severity','ref_id','details'],r.items||[])+'</div>'}
async function audit(){const r=await adminApi('/api/admin/audit'),v=$('#view');if(v)v.innerHTML='<section class="admin-title"><div><span>SECURITY HISTORY</span><h1>Audit log</h1><p>Administrative and security actions.</p></div></section><div class="card">'+table(['created_at','actor_type','actor_id','action','target_type','target_id','details'],r.items||[])+'</div>'}
async function recon(){const v=$('#view'),today=new Date().toISOString().slice(0,10);if(!v)return;v.innerHTML='<section class="admin-title"><div><span>DAILY CHECK</span><h1>Reconciliation</h1><p>Compare approved payments with ledger movement.</p></div></section><div class="card"><div class="recon-row"><input id="reconDate" type="date" value="'+today+'"><button id="runRecon">Run report</button></div><pre id="reconOut" class="json">Select a date.</pre></div>';$('#runRecon')?.addEventListener('click',async()=>{const o=$('#reconOut'),d=$<HTMLInputElement>('#reconDate')?.value;if(o)o.textContent='Loading…';try{const r=await adminApi('/api/admin/reconciliation?date='+encodeURIComponent(d||today));if(o)o.textContent=JSON.stringify(r,null,2)}catch(x:any){toast(x.message,true)}});($<HTMLButtonElement>('#runRecon'))?.click()}
async function resolveDispute(id:string,action:string){const resolution=prompt('Resolution note',action==='resolve'?'Reviewed and resolved':'Rejected after review');if(resolution==null)return;try{await adminApi('/api/admin/disputes/'+encodeURIComponent(id)+'/'+action,{method:'POST',body:{resolution}});toast('Dispute updated');pending()}catch(x:any){toast(x.message,true)}}
document.querySelector<HTMLFormElement>('#adminLoginForm')?.addEventListener('submit',login);
$('#nav')?.addEventListener('click',ev=>{const b=(ev.target as Element).closest<HTMLElement>('[data-tab]');if(b?.dataset.tab)openTab(b.dataset.tab)});
$('#closeModal')?.addEventListener('click',()=>{$('#modal')?.classList.add('hidden');const b=$('#modalBody');if(b)b.innerHTML=''});
showApp();
